using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using mewu_ai_Assistant.Interop;
using mewu_ai_Assistant.Services;
using TextBox=System.Windows.Controls.TextBox;
using Button=System.Windows.Controls.Button;
using mewu_ai_Assistant.Speech;
namespace mewu_ai_Assistant.Views;
public sealed class AiPromptWindow : Window
{
    private readonly AppHost _host;private readonly Models.ScreenRect? _region;private BitmapSource _image;private readonly Image _preview=new();private readonly TextBox _prompt=new();private readonly TextBlock _status=new();private readonly TextBlock _answer=new();private readonly Button _send=new();private readonly Canvas _annotationLayer=new();private readonly List<Models.AiMessage> _history=[new("system","分析图片时优先返回 JSON：{answer:string,annotations:[{x,y,width,height,text,type}]}。坐标必须是选区内 0 到 1 的归一化值，只标注 3 到 6 个最重要位置；不适合标注时 annotations 为空。")];private CancellationTokenSource? _request;
    public AiPromptWindow(AppHost host,BitmapSource image,bool translate=false,Models.ScreenRect? region=null)
    {
        _host=host;_image=image;_region=region;Title=translate?"喵呜AI 翻译":"喵呜AI";Width=720;Height=650;WindowStartupLocation=WindowStartupLocation.CenterScreen;Background=new SolidColorBrush(Color.FromRgb(11,16,24));Foreground=Brushes.White;
        var grid=new Grid{Margin=new Thickness(20)};grid.RowDefinitions.Add(new RowDefinition{Height=new GridLength(2,GridUnitType.Star)});grid.RowDefinitions.Add(new RowDefinition{Height=new GridLength(1,GridUnitType.Star)});grid.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});grid.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});grid.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});
        _preview.Source=image;_preview.Stretch=Stretch.Fill;_annotationLayer.Width=image.PixelWidth;_annotationLayer.Height=image.PixelHeight;var previewGrid=new Grid{Width=image.PixelWidth,Height=image.PixelHeight,Margin=new Thickness(0,0,0,14)};previewGrid.Children.Add(_preview);previewGrid.Children.Add(_annotationLayer);var previewView=new Viewbox{Stretch=Stretch.Uniform,Child=previewGrid};_answer.TextWrapping=TextWrapping.Wrap;_answer.Margin=new Thickness(0,8,0,12);_answer.Foreground=Brushes.White;var answerScroll=new ScrollViewer{Content=_answer,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};_prompt.Text=translate?"翻译成中文":"";_prompt.MinHeight=46;_prompt.Padding=new Thickness(10);_prompt.ToolTip="询问图中内容…";var actions=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right};var refresh=new Button{Content="刷新截图",Padding=new Thickness(10,9,10,9),Margin=new Thickness(0,10,8,0),IsEnabled=region is not null};refresh.Click+=(_,_)=>RefreshScreenshot();var annotations=new Button{Content="隐藏批注",Padding=new Thickness(10,9,10,9),Margin=new Thickness(0,10,8,0)};annotations.Click+=(_,_)=>{_annotationLayer.Visibility=_annotationLayer.Visibility==Visibility.Visible?Visibility.Hidden:Visibility.Visible;annotations.Content=_annotationLayer.Visibility==Visibility.Visible?"隐藏批注":"显示批注";};var copy=new Button{Content="复制答案",Padding=new Thickness(10,9,10,9),Margin=new Thickness(0,10,8,0)};copy.Click+=(_,_)=>{if(!string.IsNullOrWhiteSpace(_answer.Text))Clipboard.SetText(_answer.Text);};var mic=new Button{Content="🎤",ToolTip="语音输入",Padding=new Thickness(12,9,12,9),Margin=new Thickness(0,10,8,0)};mic.Click+=async(_,_)=>await ListenAsync(mic);_send.Content="发送";_send.Padding=new Thickness(20,9,20,9);_send.Margin=new Thickness(0,10,0,0);_send.Click+=async(_,_)=>await SendAsync();actions.Children.Add(refresh);actions.Children.Add(annotations);actions.Children.Add(copy);actions.Children.Add(mic);actions.Children.Add(_send);_status.Foreground=new SolidColorBrush(Color.FromRgb(145,160,181));_status.Text="将发送：图片 + 文字（只有点击发送后才上传）";_status.Margin=new Thickness(0,7,0,0);Grid.SetRow(answerScroll,1);Grid.SetRow(_prompt,2);Grid.SetRow(_status,3);Grid.SetRow(actions,4);grid.Children.Add(previewView);grid.Children.Add(answerScroll);grid.Children.Add(_prompt);grid.Children.Add(_status);grid.Children.Add(actions);Content=grid;
        Closed+=(_,_)=>_request?.Cancel();SourceInitialized+=(_,_)=>NativeMethods.SetWindowDisplayAffinity(new System.Windows.Interop.WindowInteropHelper(this).Handle,NativeMethods.WdaExcludeFromCapture);if(host.Settings.EnableVoiceInput&&host.Settings.AutomaticallyStartListening)Loaded+=async(_,_)=>await ListenAsync(mic);
    }
    private async Task SendAsync(){var typed=_prompt.Text;if(_history.Count==1&&(typed.Contains("翻译",StringComparison.OrdinalIgnoreCase)||typed.Contains("translate",StringComparison.OrdinalIgnoreCase))){new TranslationWindow(_host,_image).Show();Close();return;}var provider=new AiProviderFactory().Create(_host.Settings);if(provider is null){_status.Text="尚未配置 AI 模型或 API Key。请先打开设置 → AI。";_host.ShowSettings();return;}if(!provider.Capabilities.SupportsImage){_status.Text="当前 Provider 仅支持文字，不能上传图片。请切换支持图片的 Provider。";return;}_request?.Cancel();_request=new();_send.IsEnabled=false;_answer.Text="";_status.Text="正在上传并分析…（Esc 可取消）";try{var prompt=string.IsNullOrWhiteSpace(typed)?"理解当前屏幕区域，根据内容给出当前最有帮助的说明。":typed;var progress=provider.Capabilities.SupportsStreaming?new Progress<string>(delta=>_answer.Text+=delta):null;var request=new Models.AiRequest{Prompt=prompt,History=[.._history],Attachments=[new Models.AiAttachment(Models.AiAttachmentType.Image,"image/png",ScreenCaptureService.EncodePng(_image))],StreamingProgress=progress};var result=await provider.SendAsync(request,_request.Token);_answer.Text=result.Answer;_history.Add(new("user",prompt));_history.Add(new("assistant",result.Answer));var configured=_host.Settings.Providers.FirstOrDefault(x=>x.Id==provider.Id);if(_host.Settings.SaveConversationHistory)new ConversationHistoryService().Append(configured?.Name??provider.Id,configured?.Model??"",prompt,result.Answer);_prompt.Clear();RenderAnnotations(result.Annotations);_status.Text=result.Annotations.Count>0?$"完成，并返回 {result.Annotations.Count} 个屏幕批注；可继续追问。":"完成，可继续追问";}catch(OperationCanceledException){_status.Text="已取消";}catch(Exception ex){_status.Text=ex.Message;}finally{_send.IsEnabled=true;}}
    private async Task ListenAsync(Button button){button.IsEnabled=false;_status.Text="正在聆听…";try{var text=await new WindowsSpeechToTextService().RecognizeOnceAsync(_host.Settings.VoiceLanguage,CancellationToken.None);if(!string.IsNullOrWhiteSpace(text))_prompt.Text=string.IsNullOrWhiteSpace(_prompt.Text)?text:_prompt.Text+" "+text;_status.Text="语音已写入，可继续编辑后发送";}catch(Exception ex){_status.Text=$"语音不可用，仍可键盘输入：{ex.Message}";}finally{button.IsEnabled=true;}}
    private void RefreshScreenshot(){if(_region is null)return;_image=new ScreenCaptureService().CaptureRegion(_region.Value,_host.Settings.IncludeCaptureCursor);_preview.Source=_image;_annotationLayer.Children.Clear();_history.RemoveAll(x=>x.Role!="system");_answer.Text="";_status.Text="已刷新同一屏幕区域；尚未上传，可重新提问。";}
    private void RenderAnnotations(IReadOnlyList<Models.AiAnnotation> notes){_annotationLayer.Children.Clear();var width=_annotationLayer.Width;var height=_annotationLayer.Height;var cardWidth=Math.Clamp(width*.28,160,700);var fontSize=Math.Clamp(width/65,12,48);foreach(var n in notes.Take(6)){var border=new Border{BorderBrush=new SolidColorBrush(Color.FromRgb(67,168,255)),BorderThickness=new Thickness(Math.Max(2,width/900)),Background=Brushes.Transparent};Canvas.SetLeft(border,n.X*width);Canvas.SetTop(border,n.Y*height);border.Width=Math.Max(20,n.Width*width);border.Height=Math.Max(20,n.Height*height);_annotationLayer.Children.Add(border);var card=new TextBlock{Text=n.Text,Foreground=Brushes.White,Background=new SolidColorBrush(Color.FromArgb(225,8,15,25)),Padding=new Thickness(fontSize*.45),FontSize=fontSize,TextWrapping=TextWrapping.Wrap,MaxWidth=cardWidth};Canvas.SetLeft(card,Math.Clamp((n.X+n.Width)*width+8,0,Math.Max(0,width-cardWidth)));Canvas.SetTop(card,Math.Clamp(n.Y*height,0,Math.Max(0,height-fontSize*4)));_annotationLayer.Children.Add(card);}}
    protected override void OnKeyDown(System.Windows.Input.KeyEventArgs e){if(e.Key==System.Windows.Input.Key.Escape){_request?.Cancel();Close();e.Handled=true;return;}base.OnKeyDown(e);}
}
