using Microsoft.Win32;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Threading;
using mewu_ai_Assistant.Interop;
using mewu_ai_Assistant.Models;
using mewu_ai_Assistant.Recording;
using mewu_ai_Assistant.Services;

namespace mewu_ai_Assistant.Views;

public sealed class RecordingPreviewWindow : Window
{
    private readonly AppHost _host;private readonly ScreenRect _region;private readonly string _video,_frames;private readonly MediaElement _player=new(){LoadedBehavior=MediaState.Manual,UnloadedBehavior=MediaState.Close,Stretch=Stretch.Uniform};private readonly Image _framePreview=new(){Stretch=Stretch.Uniform,Visibility=Visibility.Collapsed};private readonly Slider _progress=new(){Minimum=0,Maximum=1};private readonly TextBlock _status=new();private readonly DispatcherTimer _timer=new(){Interval=TimeSpan.FromMilliseconds(250)};private readonly DispatcherTimer _frameTimer=new();private List<string> _previewFrames=[];private int _previewFrameIndex;private bool _seeking,_fallbackMode;
    public RecordingPreviewWindow(AppHost host,ScreenRect region,string video,string frames)
    {
        _host=host;_region=region;_video=video;_frames=frames;Title="喵呜AI 录屏预览";WindowStartupLocation=WindowStartupLocation.CenterScreen;WindowStyle=WindowStyle.None;ResizeMode=ResizeMode.CanResize;AllowsTransparency=true;Background=Brushes.Transparent;MinWidth=620;MinHeight=440;var ratio=Math.Clamp(region.Width/(double)Math.Max(1,region.Height),.55,2.4);Width=Math.Clamp(720*ratio,680,1080);Height=Math.Clamp(Width/ratio+150,520,820);
        _player.Source=new Uri(video);_player.MediaOpened+=(_,_)=>{_status.Text=$"{region.Width&~1} × {region.Height&~1} · {_player.NaturalDuration.TimeSpan:mm\\:ss}";_progress.Maximum=Math.Max(.1,_player.NaturalDuration.TimeSpan.TotalSeconds);};_player.MediaEnded+=(_,_)=>{_player.Position=TimeSpan.Zero;_player.Play();};_player.MediaFailed+=(_,_)=>StartFramePreview();
        var title=new Grid{Margin=new Thickness(20,12,20,12)};title.ColumnDefinitions.Add(new ColumnDefinition());title.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});var caption=new TextBlock{Text="录屏预览",FontSize=16,FontWeight=FontWeights.SemiBold,VerticalAlignment=VerticalAlignment.Center};title.Children.Add(caption);var close=Button("×",Close);close.Width=36;close.Padding=new Thickness(0,6,0,6);Grid.SetColumn(close,1);title.Children.Add(close);title.MouseLeftButtonDown+=(_,e)=>{if(e.OriginalSource is not System.Windows.Controls.Button)DragMove();};
        var videoSurface=new Grid();videoSurface.Children.Add(_player);videoSurface.Children.Add(_framePreview);var videoCard=new Border{Background=new SolidColorBrush(Color.FromRgb(29,34,43)),CornerRadius=new CornerRadius(14),Margin=new Thickness(18,0,18,10),ClipToBounds=true,Child=videoSurface};
        _progress.Margin=new Thickness(22,0,22,4);_progress.PreviewMouseDown+=(_,_)=>_seeking=true;_progress.PreviewMouseUp+=(_,_)=>{if(_fallbackMode){_previewFrameIndex=Math.Clamp((int)Math.Round(_progress.Value),0,Math.Max(0,_previewFrames.Count-1));ShowPreviewFrame();}else _player.Position=TimeSpan.FromSeconds(_progress.Value);_seeking=false;};
        var footer=new Grid{Margin=new Thickness(18,4,18,17)};footer.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});footer.ColumnDefinitions.Add(new ColumnDefinition());footer.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});var playback=new StackPanel{Orientation=Orientation.Horizontal};playback.Children.Add(Button("▶ 播放",Play));var pause=Button("Ⅱ 暂停",Pause);pause.Margin=new Thickness(7,0,0,0);playback.Children.Add(pause);footer.Children.Add(playback);_status.Text="正在加载区域录像…";_status.Foreground=new SolidColorBrush(Color.FromRgb(103,116,136));_status.VerticalAlignment=VerticalAlignment.Center;_status.HorizontalAlignment=HorizontalAlignment.Center;Grid.SetColumn(_status,1);footer.Children.Add(_status);var actions=new StackPanel{Orientation=Orientation.Horizontal};actions.Children.Add(Button("重新录制",ReRecord));var save=Button("保存 MP4",SaveMp4,true);save.Margin=new Thickness(7,0,0,0);actions.Children.Add(save);var gif=Button("导出 GIF",SaveGif);gif.Margin=new Thickness(7,0,0,0);actions.Children.Add(gif);var ask=Button("关键帧问 AI",AskKeyframes);ask.Margin=new Thickness(7,0,0,0);actions.Children.Add(ask);Grid.SetColumn(actions,2);footer.Children.Add(actions);
        var layout=new Grid();layout.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});layout.RowDefinitions.Add(new RowDefinition());layout.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});layout.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});Grid.SetRow(videoCard,1);Grid.SetRow(_progress,2);Grid.SetRow(footer,3);layout.Children.Add(title);layout.Children.Add(videoCard);layout.Children.Add(_progress);layout.Children.Add(footer);Content=new Border{Background=new SolidColorBrush(Color.FromRgb(247,249,253)),BorderBrush=new SolidColorBrush(Color.FromRgb(218,225,235)),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(20),Child=layout,Effect=new DropShadowEffect{Color=Color.FromRgb(60,73,92),BlurRadius=32,ShadowDepth=8,Opacity=.28}};
        _timer.Tick+=(_,_)=>{if(!_fallbackMode&&!_seeking&&_player.NaturalDuration.HasTimeSpan)_progress.Value=_player.Position.TotalSeconds;};_frameTimer.Tick+=(_,_)=>{if(_previewFrames.Count==0)return;_previewFrameIndex=(_previewFrameIndex+1)%_previewFrames.Count;ShowPreviewFrame();};Loaded+=(_,_)=>{_player.Play();_timer.Start();};Closed+=(_,_)=>Cleanup();SourceInitialized+=(_,_)=>NativeMethods.ExcludeFromCapture(new System.Windows.Interop.WindowInteropHelper(this).Handle);KeyDown+=(_,e)=>{if(e.Key==System.Windows.Input.Key.Escape)Close();};
    }
    private static Button Button(string text,Action action,bool primary=false){var button=new Button{Content=text,Padding=new Thickness(13,8,13,8)};button.SetResourceReference(StyleProperty,primary?"PrimaryButton":"SecondaryButton");button.Click+=(_,_)=>action();return button;}
    private void Play(){if(_fallbackMode)_frameTimer.Start();else _player.Play();}
    private void Pause(){if(_fallbackMode)_frameTimer.Stop();else _player.Pause();}
    private void StartFramePreview(){_previewFrames=Directory.Exists(_frames)?Directory.EnumerateFiles(_frames,"*.png").OrderBy(x=>x).ToList():[];if(_previewFrames.Count==0){_status.Text="系统播放器不可用，且没有可预览的关键帧";return;}_fallbackMode=true;_player.Visibility=Visibility.Collapsed;_framePreview.Visibility=Visibility.Visible;_progress.Maximum=Math.Max(1,_previewFrames.Count-1);_frameTimer.Interval=TimeSpan.FromMilliseconds(Math.Max(67,1000/Math.Clamp(_host.Settings.GifFps,1,15)));_status.Text=$"本地关键帧预览 · {_region.Width&~1} × {_region.Height&~1}";ShowPreviewFrame();_frameTimer.Start();}
    private void ShowPreviewFrame(){if(_previewFrames.Count==0)return;using var stream=File.OpenRead(_previewFrames[_previewFrameIndex]);_framePreview.Source=new System.Windows.Media.Imaging.PngBitmapDecoder(stream,System.Windows.Media.Imaging.BitmapCreateOptions.PreservePixelFormat,System.Windows.Media.Imaging.BitmapCacheOption.OnLoad).Frames[0];if(!_seeking)_progress.Value=_previewFrameIndex;}
    private void ReRecord(){Close();Dispatcher.BeginInvoke(_host.BeginCapture);}
    private void SaveMp4(){var dialog=new SaveFileDialog{Filter="MP4 视频|*.mp4",DefaultExt=".mp4"};if(dialog.ShowDialog(this)==true){File.Copy(_video,dialog.FileName,true);_host.Notify("MP4 已保存");}}
    private void SaveGif(){var dialog=new SaveFileDialog{Filter="GIF 动图|*.gif",DefaultExt=".gif"};if(dialog.ShowDialog(this)==true){try{GifExportService.Export(_frames,dialog.FileName,_host.Settings.GifFps);_host.Notify("GIF 已保存");}catch(Exception ex){MessageBox.Show(ex.Message,"GIF 导出失败");}}}
    private void AskKeyframes(){try{var files=Directory.EnumerateFiles(_frames,"*.png").OrderBy(x=>x).ToList();if(files.Count==0)throw new InvalidOperationException("没有可分析的关键帧");var selected=new[]{files[0],files[files.Count/2],files[^1]}.Distinct().ToList();var images=selected.Select(file=>{using var stream=File.OpenRead(file);return (System.Windows.Media.Imaging.BitmapSource)new System.Windows.Media.Imaging.PngBitmapDecoder(stream,System.Windows.Media.Imaging.BitmapCreateOptions.PreservePixelFormat,System.Windows.Media.Imaging.BitmapCacheOption.OnLoad).Frames[0];}).ToList();var width=images.Max(x=>x.PixelWidth);var height=images.Sum(x=>x.PixelHeight);var visual=new DrawingVisual();using(var drawing=visual.RenderOpen()){var y=0d;foreach(var image in images){drawing.DrawImage(image,new Rect(0,y,width,image.PixelHeight));y+=image.PixelHeight;}}var sheet=new System.Windows.Media.Imaging.RenderTargetBitmap(width,height,96,96,PixelFormats.Pbgra32);sheet.Render(visual);new AiPromptWindow(_host,sheet,false,null,"这是一段区域录像的开始、中间、结束关键帧，请按时间顺序分析变化。").Show();}catch(Exception ex){MessageBox.Show(ex.Message,"无法分析录像");}}
    private void Cleanup(){_timer.Stop();_frameTimer.Stop();_framePreview.Source=null;_player.Stop();_player.Close();try{if(File.Exists(_video))File.Delete(_video);}catch{}try{if(Directory.Exists(_frames))Directory.Delete(_frames,true);}catch{}}
}
