using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using mewu_ai_Assistant.Services;
using ComboBox=System.Windows.Controls.ComboBox;
using TextBox=System.Windows.Controls.TextBox;
using CheckBox=System.Windows.Controls.CheckBox;
using Button=System.Windows.Controls.Button;
namespace mewu_ai_Assistant.Views;
public sealed class SettingsWindow : Window
{
    private readonly AppHost _host; private readonly ComboBox _delay=new(),_providerType=new(),_hotkey=new(); private readonly TextBox _baseUrl=new(),_model=new(); private readonly PasswordBox _apiKey=new(); private readonly CheckBox _history=new(),_voice=new(),_autoVoice=new(),_startup=new(),_ctrl=new(),_shift=new(),_alt=new();
    public SettingsWindow(AppHost host)
    {
        _host=host;Title="喵呜AI 设置";Width=720;Height=600;WindowStartupLocation=WindowStartupLocation.CenterScreen;Background=new SolidColorBrush(Color.FromRgb(11,16,24));Foreground=Brushes.White;
        var tabs=new TabControl{Margin=new Thickness(20)};tabs.Items.Add(Tab("常规",General()));tabs.Items.Add(Tab("捕获",Capture()));tabs.Items.Add(Tab("录屏",Text("录屏帧率与鼠标指针设置将在录屏后端启用。")));tabs.Items.Add(Tab("AI",Ai()));tabs.Items.Add(Tab("语音",Voice()));tabs.Items.Add(Tab("隐私",Privacy()));
        var save=new Button{Content="保存",Padding=new Thickness(24,9,24,9),Margin=new Thickness(0,0,20,20),HorizontalAlignment=HorizontalAlignment.Right};save.Click+=(_,_)=>Save();var grid=new Grid();grid.RowDefinitions.Add(new RowDefinition());grid.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});Grid.SetRow(save,1);grid.Children.Add(tabs);grid.Children.Add(save);Content=grid;
    }
    private static TabItem Tab(string h,UIElement c)=>new(){Header=h,Content=c};private static TextBlock Text(string t)=>new(){Text=t,Margin=new Thickness(20),TextWrapping=TextWrapping.Wrap};
    private UIElement General(){var p=Panel();_startup.Content="登录 Windows 后自动启动";_startup.IsChecked=_host.Settings.LaunchAtStartup;p.Children.Add(_startup);p.Children.Add(Text("全局截图快捷键"));var mods=new StackPanel{Orientation=Orientation.Horizontal};_ctrl.Content="Ctrl";_shift.Content="Shift";_alt.Content="Alt";_ctrl.IsChecked=_host.Settings.CaptureHotkey.Modifiers.HasFlag(System.Windows.Input.ModifierKeys.Control);_shift.IsChecked=_host.Settings.CaptureHotkey.Modifiers.HasFlag(System.Windows.Input.ModifierKeys.Shift);_alt.IsChecked=_host.Settings.CaptureHotkey.Modifiers.HasFlag(System.Windows.Input.ModifierKeys.Alt);mods.Children.Add(_ctrl);mods.Children.Add(_shift);mods.Children.Add(_alt);p.Children.Add(mods);foreach(var key in Enumerable.Range('A',26).Select(x=>((char)x).ToString()))_hotkey.Items.Add(key);_hotkey.SelectedItem=_host.Settings.CaptureHotkey.Key.ToString();p.Children.Add(_hotkey);p.Children.Add(Text("关闭主窗口不会退出；请使用托盘菜单退出。"));return p;}
    private UIElement Capture(){var p=Panel();p.Children.Add(Text("延时截图"));foreach(var i in new[]{0,3,5})_delay.Items.Add($"{i} 秒");_delay.SelectedIndex=_host.Settings.CaptureDelaySeconds switch{3=>1,5=>2,_=>0};p.Children.Add(_delay);return p;}
    private UIElement Ai(){var p=Panel();p.Children.Add(Text("API Key 使用 Windows DPAPI 加密，仅保存在本机当前用户目录。"));_providerType.Items.Add("OpenAICompatible");_providerType.Items.Add("MiniMax");p.Children.Add(_providerType);p.Children.Add(Label("Base URL",_baseUrl));p.Children.Add(Label("Model",_model));var keyPanel=Panel();keyPanel.Children.Add(Text("API Key（留空则保留现有密钥）"));_apiKey.Margin=new Thickness(0,4,0,12);_apiKey.Padding=new Thickness(8);keyPanel.Children.Add(_apiKey);p.Children.Add(keyPanel);var provider=_host.Settings.Providers.FirstOrDefault();_providerType.SelectedIndex=provider?.Type=="MiniMax"?1:0;_baseUrl.Text=provider?.BaseUrl??"https://api.openai.com/v1";_model.Text=provider?.Model??"gpt-4.1-mini";return p;}
    private UIElement Voice(){var p=Panel();_voice.Content="启用语音输入";_voice.IsChecked=_host.Settings.EnableVoiceInput;_autoVoice.Content="Prompt 出现时自动监听";_autoVoice.IsChecked=_host.Settings.AutomaticallyStartListening;p.Children.Add(_voice);p.Children.Add(_autoVoice);return p;}
    private UIElement Privacy(){var p=Panel();_history.Content="在本地保存 AI 对话历史";_history.IsChecked=_host.Settings.SaveConversationHistory;p.Children.Add(_history);p.Children.Add(Text("媒体默认不永久保存；截图只有明确发送 AI 时才会上传。"));var clearHistory=new Button{Content="清空本地对话历史",Padding=new Thickness(12,6,12,6),Margin=new Thickness(0,10,0,0)};clearHistory.Click+=(_,_)=>{new ConversationHistoryService().Clear();MessageBox.Show("本地对话历史已清空","喵呜AI");};p.Children.Add(clearHistory);var clear=new Button{Content="清理临时媒体",Padding=new Thickness(12,6,12,6),Margin=new Thickness(0,8,0,0)};clear.Click+=(_,_)=>{new TempFileService().Cleanup(TimeSpan.Zero);MessageBox.Show("临时媒体已清理","喵呜AI");};p.Children.Add(clear);var open=new Button{Content="打开数据目录",Padding=new Thickness(12,6,12,6),Margin=new Thickness(0,8,0,0)};open.Click+=(_,_)=>System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"MewuAI")){UseShellExecute=true});p.Children.Add(open);p.Children.Add(Text($"应用版本：{typeof(SettingsWindow).Assembly.GetName().Version}\n.NET：{Environment.Version}\nWindows：{Environment.OSVersion.Version}\n捕获：GDI desktop snapshot / Windows OCR\n录屏：Media Foundation H.264"));return p;}
    private static StackPanel Panel()=>new(){Margin=new Thickness(20)};private static FrameworkElement Label(string name,TextBox box){var p=Panel();p.Children.Add(Text(name));box.Margin=new Thickness(0,4,0,12);box.Padding=new Thickness(8);p.Children.Add(box);return p;}
    private void Save(){_host.Settings.LaunchAtStartup=_startup.IsChecked==true;StartupService.SetEnabled(_host.Settings.LaunchAtStartup);var mods=System.Windows.Input.ModifierKeys.None;if(_ctrl.IsChecked==true)mods|=System.Windows.Input.ModifierKeys.Control;if(_shift.IsChecked==true)mods|=System.Windows.Input.ModifierKeys.Shift;if(_alt.IsChecked==true)mods|=System.Windows.Input.ModifierKeys.Alt;if(_hotkey.SelectedItem is string key&&Enum.TryParse<System.Windows.Input.Key>(key,out var parsed)){_host.Settings.CaptureHotkey.Key=parsed;_host.Settings.CaptureHotkey.Modifiers=mods;}_host.Settings.CaptureDelaySeconds=_delay.SelectedIndex switch{1=>3,2=>5,_=>0};_host.Settings.EnableVoiceInput=_voice.IsChecked==true;_host.Settings.AutomaticallyStartListening=_autoVoice.IsChecked==true;_host.Settings.SaveConversationHistory=_history.IsChecked==true;if(!string.IsNullOrWhiteSpace(_baseUrl.Text)){var p=_host.Settings.Providers.FirstOrDefault();if(p is null){p=new();_host.Settings.Providers.Add(p);_host.Settings.DefaultProviderId=p.Id;}p.Type=_providerType.SelectedIndex==1?"MiniMax":"OpenAICompatible";p.Name=p.Type;p.BaseUrl=_baseUrl.Text.TrimEnd('/');p.Model=_model.Text;if(!string.IsNullOrWhiteSpace(_apiKey.Password)){if(string.IsNullOrWhiteSpace(p.CredentialId))p.CredentialId=Guid.NewGuid().ToString("N");new CredentialService().Save(p.CredentialId,_apiKey.Password);}}_host.SaveSettings();Close();}
}
