// node --experimental-vm-modules apps/desktop/src/memory-provider.test.mjs
// Synthetic IPC and bounded state only. No server, bank, secret store or user data.
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { stripTypeScriptTypes } from 'node:module';
import { SourceTextModule, SyntheticModule, createContext } from 'node:vm';
import { webcrypto } from 'node:crypto';
import { loadProviderPresets, loadAssetImport, loadGeometryHistory } from './geometry-test-module.mjs';
const source = async file => stripTypeScriptTypes(await readFile(new URL(file, import.meta.url), 'utf8'), { mode: 'transform' });
const synthetic = values => new SyntheticModule(Object.keys(values), function () { for (const [key, value] of Object.entries(values)) this.setExport(key, value); });
const checks = [];
const helper = new SourceTextModule(await source('./memory-provider-state.ts'));
await helper.link(() => { throw Error('Unexpected policy dependency'); }); await helper.evaluate();
const h = helper.namespace;
assert.equal(h.normalizeMemoryEndpoint(' https://service.example/base/ '), 'https://service.example/base');
for (const url of ['http://localhost:8888/', 'http://127.0.0.1/base', 'http://[::1]:8888']) assert.ok(h.normalizeMemoryEndpoint(url).startsWith('http:'));
for (const url of ['http://service.example', 'https://user:pw@service.example', 'https://service.example/?key=value', 'https://service.example/#x', 'file:///tmp/x']) assert.throws(() => h.normalizeMemoryEndpoint(url));
checks.push('Endpoint preserves valid base prefix, requires TLS except loopback and rejects URL credentials/query/fragment');
const view = (state, extra = {}) => ({ state, reason: null, forgotten: null, ...extra });
assert.equal(h.memoryEvidenceLabel(view('accepted')), '远端处理中');
assert.equal(h.memoryEvidenceLabel(view('unknown')), '结果待确认');
for (const remoteState of ['pending', 'currently_absent', 'unknown', 'failed', 'needs_authorization']) {
  const label = h.memoryEvidenceLabel(view('suppressed', { forgotten: { localSuppressed: true, remoteState, quiescence: 'unproven' } }));
  assert.ok(label.startsWith('不再使用')); assert.ok(!label.includes('远端已删除'));
}
assert.ok(!h.memoryEvidenceLabel(view('suppressed', { forgotten: { localSuppressed: true, remoteState: 'confirmed_deleted', quiescence: 'unproven' } })).includes('远端已删除'));
assert.equal(h.memoryEvidenceLabel(view('suppressed', { forgotten: { localSuppressed: true, remoteState: 'confirmed_deleted', quiescence: 'proven' } })), '不再使用 · 远端已删除');
checks.push('Accepted/unknown and every tombstone state remain truthful; final deletion requires confirmed+quiescent');
const binding = { id: 'binding-a', revision: 2, ledgerRevision: 9, policy: { completedTurnSync: false }, pendingCount: 2, evidenceCount: 3, blockedCount: 0, deletionPendingCount: 1 };
const old = { selection: { revision: 5, bindingId: 'binding-a' }, bindings: [binding], nextCursor: null };
assert.equal(h.mergeMemoryStatus(old, { ...old, selection: { revision: 4, bindingId: null } }), old);
const merged = h.mergeMemoryStatus(old, { ...old, bindings: [{ ...binding, revision: 3, ledgerRevision: 8, policy: { completedTurnSync: true }, evidenceCount: 2 }] });
assert.equal(merged.bindings[0].revision, 3); assert.equal(merged.bindings[0].policy.completedTurnSync, true); assert.equal(merged.bindings[0].ledgerRevision, 9); assert.equal(merged.bindings[0].evidenceCount, 3);
const newerLedger = h.mergeMemoryStatus(merged, { ...old, bindings: [{ ...binding, ledgerRevision: 10, evidenceCount: 4 }] });
assert.equal(newerLedger.bindings[0].revision, 3); assert.equal(newerLedger.bindings[0].ledgerRevision, 10); assert.equal(newerLedger.bindings[0].evidenceCount, 4);
checks.push('Older selection cannot revert source; ledger and authorization revisions merge independently');
assert.equal(h.memorySelectionSettled({ revision: 7, bindingId: 'b' }, { revision: 6, bindingId: 'a' }), false);
assert.equal(h.memorySelectionSettled({ revision: 6, bindingId: 'a' }, { revision: 6, bindingId: 'a' }), true);
const ownPolicy = { ...binding, revision: 3, policy: { completedTurnSync: true } };
assert.equal(h.memoryPolicySettled(2, true, ownPolicy, { ...ownPolicy, revision: 4 }), false);
assert.equal(h.memoryPolicySettled(2, true, ownPolicy, ownPolicy), true);
assert.equal(h.memoryPolicySettled(2, true, { ...ownPolicy, revision: 5 }, { ...ownPolicy, revision: 5 }), false);
checks.push('Mutation acknowledgement never upgrades draft CAS to a later external revision or clears a conflicted choice');
const scope = new h.MemoryRequestScope(), oldReply = scope.capture();
scope.invalidate(); assert.equal(oldReply(), false);
const currentReply = scope.capture(); assert.equal(currentReply(), true);
scope.dispose(); assert.equal(currentReply(), false); assert.equal(scope.capture()(), false);
checks.push('Agent/form/visibility generation invalidation and disposal reject late foreground completion');
assert.equal(h.manualMemoryText('  中文  '), '中文');
assert.throws(() => h.manualMemoryText('a\0b'), /无效/);
assert.throws(() => h.manualMemoryText('中'.repeat(22_000)), /64 KiB/);
assert.equal(h.manualMemoryText('x'.repeat(65_536)).length, 65_536);
checks.push('Manual evidence limit counts UTF-8 bytes, never silently truncates and rejects NUL');
async function bridge(native) {
  const calls = [], events = new Map(); let stops = 0;
  const module = new SourceTextModule(await source('./memory-provider-bridge.ts'));
  await module.link(name => name.endsWith('/core') ? synthetic({ isTauri: () => native, invoke: async (name, args) => { calls.push({ name, args }); return { marker: name }; } }) : synthetic({ listen: async (name, callback) => { events.set(name, callback); return () => { stops++; }; } }));
  await module.evaluate(); return { api: module.namespace, calls, events, stops: () => stops };
}
const native = await bridge(true), args = { requestId: 'request-a', agentId: 'agent-a', pluginId: 'mewu.memory-hindsight', pluginRevision: 2, contributionId: 'hindsight', endpoint: 'https://example.test/base', apiKey: 'synthetic-key' };
await native.api.probeMemoryProvider(args); await native.api.createMemoryBinding({ ...args, expectedProviderRevision: 4 });
await native.api.selectMemoryProvider({ agentId: 'agent-a', expectedProviderRevision: 4, bindingId: null, expectedBindingRevision: null });
await native.api.getMemoryProviderState({ agentId: 'agent-a' });
await native.api.externalMemoryPage({ agentId: 'agent-a', bindingId: 'binding-a' });
await native.api.externalMemoryEntry({ agentId: 'agent-a', bindingId: 'binding-a', evidenceId: 'evidence-a' });
await native.api.setMemorySync({ agentId: 'agent-a', bindingId: 'binding-a', expectedBindingRevision: 2, completedTurnSync: true });
await native.api.queueExternalMemory({ agentId: 'agent-a', bindingId: 'binding-a', expectedBindingRevision: 2, requestId: 'request-b', text: '合成记录' });
await native.api.forgetExternalMemory({ agentId: 'agent-a', bindingId: 'binding-a', evidenceId: 'evidence-a', expectedRevision: 8 });
await native.api.retireMemoryBinding({ agentId: 'agent-a', bindingId: 'binding-a', expectedBindingRevision: 3 });
await native.api.cancelMemoryRequest('request-a');
assert.deepEqual(native.calls.map(call => call.name), ['probe_memory_provider', 'create_memory_binding', 'select_memory_provider', 'get_memory_provider_state', 'external_memory_page', 'external_memory_entry', 'set_memory_sync', 'queue_external_memory', 'forget_external_memory', 'retire_memory_binding', 'cancel_memory_request']);
assert.deepEqual(native.calls[0].args, args);
assert.equal(native.calls[3].args.limit, 25); assert.equal(native.calls[4].args.query, '');
assert.ok(native.calls.slice(2).every(call => !('apiKey' in call.args)));
checks.push('Exact IPC arguments preserve request/Agent/binding revisions; only explicit probe/create receive independent key');
const received = [], stop = await native.api.subscribeMemoryProvider(id => received.push(id));
native.events.get('memory-state')({ payload: { agentId: 'agent-a' } });
native.events.get('memory-state')({ payload: { anything: true } }); stop();
native.events.get('memory-state')({ payload: { agentId: 'agent-b' } });
assert.deepEqual(received, ['agent-a']); assert.equal(native.stops(), 1);
const preview = await bridge(false);
await assert.rejects(preview.api.probeMemoryProvider(args), /桌面版/);
await assert.rejects(preview.api.createMemoryBinding({ ...args, expectedProviderRevision: 0 }), /桌面版/);
await assert.rejects(preview.api.queueExternalMemory({ agentId: 'agent-a', bindingId: 'binding-a', expectedBindingRevision: 0, requestId: 'q', text: 'x' }), /桌面版/);
await preview.api.cancelMemoryRequest('request-a'); assert.equal(preview.calls.length, 0);
checks.push('State event exposes only invalidation and unsubscription gates late events; browser never fakes external success');
const context = createContext({ crypto: webcrypto, structuredClone, Date, Map, Set, Blob, File, URL, setTimeout, clearTimeout, TextEncoder, TextDecoder });
const moduleSource = async file => new SourceTextModule(await source(file), { context });
const connection = await moduleSource('./connection-policy.ts'), mosaic = await moduleSource('./mosaic-preview.ts');
await connection.link(() => { throw Error('Unexpected connection import'); }); await mosaic.link(() => { throw Error('Unexpected mosaic import'); });
const assets = await loadAssetImport(context), history = await loadGeometryHistory(context);
const coreMock = new SyntheticModule(['isTauri', 'invoke'], function () { this.setExport('isTauri', () => false); this.setExport('invoke', () => { throw Error('Unexpected native call'); }); }, { context });
const eventMock = new SyntheticModule(['listen'], function () { this.setExport('listen', async () => () => {}); }, { context });
const actualBridge = new SourceTextModule(await source('./bridge.ts'), { context, initializeImportMeta: meta => { meta.glob = () => ({}); } });
await actualBridge.link(async name => name === './provider-presets' ? await loadProviderPresets(context) : name === './asset-import' ? assets : name === './region-geometry-history' ? history : name === './connection-policy' ? connection : name === './mosaic-preview' ? mosaic : name.endsWith('/core') ? coreMock : eventMock);
await actualBridge.evaluate();
let realPreview = await actualBridge.namespace.getSnapshot();
assert.equal(realPreview.agents[0].memoryProvider.bindingId, null); assert.equal(realPreview.agents[0].memoryProvider.revision, 0);
realPreview = await actualBridge.namespace.applyCommand({ type: 'save_agent', agent: { ...realPreview.agents[0], name: '修改角色', memoryProvider: { revision: 99, bindingId: 'forged-remote' } } });
assert.equal(realPreview.agents[0].memoryProvider.bindingId, null); assert.equal(realPreview.agents[0].memoryProvider.revision, 0);
checks.push('Real preview bridge normalizes local default and refuses provider injection through a whole Agent draft');
const config = JSON.parse(await readFile(new URL('../src-tauri/tauri.conf.json', import.meta.url), 'utf8'));
const capabilitiesUrl = new URL('../src-tauri/capabilities/', import.meta.url);
const capabilities = await Promise.all((await readdir(capabilitiesUrl)).filter(name => name.endsWith('.json')).map(async name => JSON.parse(await readFile(new URL(name, capabilitiesUrl), 'utf8'))));
const permissions = native.calls.map(call => `allow-${call.name.replaceAll('_', '-')}`);
const settings = capabilities.find(value => value.identifier === 'settings');
assert.ok(config.app.security.capabilities.includes(settings.identifier)); assert.deepEqual(settings.windows, ['settings']);
assert.ok(permissions.every(permission => settings.permissions.includes(permission)));
for (const value of capabilities.filter(value => value !== settings)) assert.ok(permissions.every(permission => !value.permissions.includes(permission)), `${value.identifier} must not manage external memory`);
checks.push('Actual Tauri capability allowlist grants provider keys/management only to settings, never space/artifact/control windows');
console.log(JSON.stringify({ passed: checks.length, checks }, null, 2));
