// Actual screenshot adapter/bridge, synthetic IPC only; no native state or device.
import assert from 'node:assert/strict';
import test from 'node:test';
import {readFile} from 'node:fs/promises';
import {stripTypeScriptTypes} from 'node:module';
import {SourceTextModule,SyntheticModule} from 'node:vm';
import {parse} from '@babel/parser';
const raw=path=>readFile(new URL(path,import.meta.url),'utf8');
const transform=source=>stripTypeScriptTypes(source,{mode:'transform'});
const synthetic=values=>new SyntheticModule(Object.keys(values),function(){for(const [key,value]of Object.entries(values))this.setExport(key,value);});
async function pure(path){const module=new SourceTextModule(transform(await raw(path)));await module.link(()=>{throw Error('unexpected dependency');});await module.evaluate();return module.namespace;}
const deps=Object.assign({},await pure('./components/drawing-properties.ts'),await pure('./drawing-layout-preview.ts'),await pure('./drawing-document.ts'));
const bridgeRaw=await raw('./raster-edit-bridge.ts');let desktop=true, calls=[],receipt;
const bridge=new SourceTextModule(transform(bridgeRaw));await bridge.link(()=>synthetic({isTauri:()=>desktop,invoke:async(name,args)=>{calls.push({name,args});return receipt;}}));await bridge.evaluate();
const code=await raw('./components/DrawingEditor.tsx'),ast=parse(code,{sourceType:'module',plugins:['typescript','jsx']});
const body=ast.program.body.find(node=>node.type==='ExportDefaultDeclaration').declaration.body.body;
const portCode=body.filter(node=>node.type!=='ReturnStatement').map(node=>{let text=code.slice(node.start,node.end);if(node.type==='VariableDeclaration'&&node.declarations[0].id.name==='port'){const render=node.declarations[0].init.properties.find(p=>p.key.name==='render').value;text=text.slice(0,render.start-node.start)+'()=>undefined'+text.slice(render.end-node.start);}return text;}).join('\n');
const adapter=new SourceTextModule(transform(`import { drawingDraftKey,drawingPropertyCommand,richPreviewTarget,richSourceIdentity,usesDrawingDocument,richDocumentHistoryStep,applyRasterEdit } from 'deps';const mosaicBlockSize=()=>8,getMosaicPreview=async()=>{};export function screenshotPort(props){${portCode};return port;}`));await adapter.link(()=>synthetic({...deps,applyRasterEdit:bridge.namespace.applyRasterEdit}));await adapter.evaluate();
const asset={id:'source',name:'synthetic.png',kind:'image',path:'synthetic',width:400,height:300};
function props(){const received=[];return {sceneId:'scene',backgroundId:asset.id,background:asset,sourceRegion:{id:'region',x:20,y:30,width:200,height:100,drawingRevision:0,drawings:[],drawingHistory:{undo:[],redo:[]}},region:{id:'region',x:20,y:30,width:200,height:100,drawingRevision:0,drawings:[]},backgroundWidth:400,backgroundHeight:300,onRasterSnapshot:v=>received.push(v),received};}
test('real bridge copies original source and points before IPC; snapshot/selected receipt remains exact',async()=>{calls=[];desktop=true;receipt={snapshot:{revision:12},selectedId:'extracted'};const target={sceneId:'scene',background:structuredClone(asset),region:{id:'region',x:0,y:0,width:400,height:300}};const points=[{x:20,y:20},{x:40,y:40}];const pending=bridge.namespace.applyRasterEdit(target,'extract',points,32);target.background.width=999;points[0].x=999;assert.equal((await pending).selectedId,'extracted');assert.equal(calls[0].name,'apply_raster_edit');assert.equal(calls[0].args.target.background.width,400);assert.equal(calls[0].args.points[0].x,20);assert.equal(calls[0].args.target.region.width,400);});
test('browser and malformed strokes reject without IPC; no silent simulated native repair',async()=>{calls=[];desktop=false;await assert.rejects(bridge.namespace.applyRasterEdit({},'heal',[{x:1,y:2}],32));assert.equal(calls.length,0);desktop=true;for(const [mode,points,width]of [['extract',[{x:1,y:2}],32],['heal',[],32],['heal',[{x:NaN,y:2}],32],['heal',[{x:1,y:2}],Infinity]])await assert.rejects(bridge.namespace.applyRasterEdit({},mode,points,width));assert.equal(calls.length,0);});
test('screenshot adapter uses stable raster port, source Region and real snapshot callback',async()=>{calls=[];desktop=true;receipt={snapshot:{revision:13},selectedId:'lifted'};const p=props(),port=adapter.namespace.screenshotPort(p);assert.equal(port.raster,port.raster);const value=await port.raster.apply('extract',[{x:30,y:40},{x:60,y:70}],32);assert.equal(value.selectedId,'lifted');assert.equal(p.received[0],receipt.snapshot);assert.equal(calls[0].args.target.region.x,20);assert.equal(calls[0].args.target.region.y,30);assert.equal(calls[0].args.points[0].x,30);});
test('long-image adapter keeps original placement Region, while stroke stays override physical pixels',async()=>{calls=[];desktop=true;receipt={snapshot:{revision:14},selectedId:null};const p=props();p.sourceRegion.imageOverride={...asset,id:'long',width:240,height:2800};p.region={...p.sourceRegion,x:0,y:0,width:240,height:2800};p.backgroundWidth=240;p.backgroundHeight=2800;const port=adapter.namespace.screenshotPort(p);assert.deepEqual(JSON.parse(JSON.stringify(port.frame())),{x:0,y:0,width:240,height:2800});await port.raster.apply('heal',[{x:10,y:2600}],32);assert.equal(calls[0].args.target.region.x,20);assert.equal(calls[0].args.target.region.imageOverride.height,2800);assert.equal(calls[0].args.points[0].y,2600);});
test('repair cannot be selected or styled; extracted layers use immutable rich document movement/history',()=>{const p=props(),port=adapter.namespace.screenshotPort(p);assert.equal(port.canSelect({kind:'rich',rich:{kind:'repair'}}),false);assert.equal(port.canSelect({kind:'rich',rich:{kind:'extracted'}}),true);assert.equal(port.canStyle({kind:'rich',rich:{kind:'extracted'}}),false);p.documentOnly=true;assert.equal(port.raster,undefined);p.documentOnly=false;p.background=undefined;assert.equal(port.raster,undefined);});
