import assert from 'node:assert/strict';import {readFile}from'node:fs/promises';import{stripTypeScriptTypes}from'node:module';import{SourceTextModule,SyntheticModule}from'node:vm';import{parse}from'@babel/parser';import test from'node:test';
const plain=x=>JSON.parse(JSON.stringify(x)),raw=url=>readFile(new URL(url,import.meta.url),'utf8'),transform=x=>stripTypeScriptTypes(x,{mode:'transform'}),synthetic=v=>new SyntheticModule(Object.keys(v),function(){for(const[k,value]of Object.entries(v))this.setExport(k,value);});
async function pure(url){const m=new SourceTextModule(transform(await raw(url)));await m.link(()=>{throw Error('Unexpected import');});await m.evaluate();return m.namespace;}
const properties=await pure('./components/drawing-properties.ts'),completion=await pure('./capture-completion.ts'),eraser=await pure('./components/drawing-eraser.ts');
const code=await raw('components/SharedDrawingEditor.tsx'),ast=parse(code,{sourceType:'module',plugins:['typescript','jsx']}),body=ast.program.body.find(node=>node.type==='ExportDefaultDeclaration').declaration.body.body;
const declaration=name=>{const node=body.find(n=>n.type==='FunctionDeclaration'?n.id.name===name:n.type==='VariableDeclaration'&&n.declarations.some(d=>d.id.name===name));assert.ok(node,name);return code.slice(node.start,node.end);};
const actual=['cacheKey','gestureIdentity','point','target','editableIds','storeEdit','cancelEdit','cancelUserEdit','commit','openText','saveText','done','beginStored','ensureSelection','doubleClick'].map(declaration).join('\n');
const m=new SourceTextModule(transform(`import {drawingDrafts,settleDrawingEdit,finishDrawing,propertyDraft,eraserHit}from'deps';export function fixture(props,svg,window){let disposed=false,serial=0,flight,tableCopy,cancelGesture,refreshConstraint,selectionSerial=0,textarea;let pendingValue=false,finishingValue=false,editValue,draft,storedDraft,selectedId='stored',reading=false,toolValue='select';const tool=()=>toolValue,setTool=v=>toolValue=v,edit=()=>editValue,textEditor=()=>edit()?.mode==='text'?edit():undefined,pending=()=>pendingValue,finishing=()=>finishingValue,selected=()=>selectedId;const setSelected=v=>selectedId=v,setPending=v=>pendingValue=v,setFinishing=v=>finishingValue=v,setEdit=v=>editValue=v,setDraft=v=>draft=v,setStoredDraft=v=>storedDraft=v,setSelectionReading=v=>reading=v;const drawings=()=>props.port.drawings?.()??[],identity=()=>cacheKey(),disabled=()=>pending()||finishing()||props.busy||props.inputLocked,report=e=>props.onError(e.message),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));${actual};return{beginStored,doubleClick,saveText,done,ensureSelection,cancelUserEdit,setEdit:v=>storeEdit(v),selected:v=>selectedId=v,pending,reading:()=>reading,edit,draft:()=>draft,storedDraft:()=>storedDraft,hasGesture:()=>!!cancelGesture,cancel:()=>cancelGesture?.(),dispose:()=>{disposed=true;cancelGesture?.();},flush:async active=>{const origin=identity();cancelGesture?.();if(flight&&!(await flight))throw Error('未保存');if(!active()||disposed||origin!==identity())throw Error('切换');if(!(await saveText(true,()=>active()&&!disposed&&origin===identity())))throw Error('未保存');}};}`));await m.link(()=>synthetic({...properties,...completion,...eraser}));await m.evaluate();
class Events{listeners=new Map();addEventListener(k,f){if(!this.listeners.has(k))this.listeners.set(k,new Set());this.listeners.get(k).add(f);}removeEventListener(k,f){this.listeners.get(k)?.delete(f);}emit(e){for(const f of [...this.listeners.get(e.type)??[]])f(e);}count(){return[...this.listeners.values()].reduce((s,v)=>s+v.size,0);}}
const deferred=()=>{let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j;});return{promise,resolve,reject};};const tick=()=>new Promise(r=>setImmediate(r));
function setup(){const commands=[],errors=[],out=[],window=new Events(),svg=new Events(),frame={x:0,y:0,width:100,height:100};svg.getBoundingClientRect=()=>({left:10,top:20,width:200,height:50});svg.captured=undefined;svg.setPointerCapture=id=>svg.captured=id;svg.hasPointerCapture=id=>svg.captured===id;svg.releasePointerCapture=id=>{svg.captured=undefined;svg.emit(event('lostpointercapture',0,0));};
const props={box:{x:10,y:20,width:200,height:50},busy:false,inputLocked:false,retainOnDone:true,port:{frame:()=>frame,sourceSize:()=>({width:100,height:100}),sourceIdentity:()=>props.source,draftKey:()=>JSON.stringify(['scene','videoDrawing','source']),revision:()=>props.revision,allows:()=>true,stored:()=>[{id:'stored',kind:'vector',bounds:{x:20,y:30,width:24,height:26}}],storedMove:(_id,b,d)=>({...b,x:Math.floor(b.x+d.x+.5),y:Math.floor(b.y+d.y+.5)}),propertyCommand:d=>properties.draftChanged(d)?{type:d.base?'update_drawing':'add_drawing',drawing:d.drawing,expectedRevision:d.expectedRevision}:undefined,persistedId:id=>id},source:'sourceA',revision:5,onCommand:async c=>{commands.push(plain(c));},onError:e=>errors.push(e),onClose:()=>out.push('close'),onExport:async()=>{out.push('export');return true;}};return{...m.namespace.fixture(props,svg,window),props,commands,errors,out,svg,window};}
function event(type,x,y,extra={}){return{type,button:0,pointerId:3,buttons:type==='pointerup'?0:1,clientX:10+x*2,clientY:20+y*.5,preventDefault(){},stopPropagation(){},...extra};}
const draw={id:'draft',kind:'text',color:'#ff0000',strokeWidth:1,points:[{x:5,y:6}],text:'draft',fontSize:20};
test('real shared compact Move previews under independent DOM ratios then one CAS; click/cancel/lost/blur-source-like/lock do not write',async()=>{
const f=setup();f.beginStored(event('pointerdown',25,35),'stored');f.window.emit(event('pointermove',35.4,47.5));assert.deepEqual(plain(f.storedDraft().bounds),{x:30,y:43,width:24,height:26});assert.equal(f.commands.length,0);f.window.emit(event('pointerup',35.4,47.5));await tick();assert.equal(f.commands.length,1);assert.equal(f.commands[0].type,'move_stored');assert.equal(f.window.count(),0);
for(const mode of ['click','cancel','lost','source','revision','lock','dispose']){const v=setup();v.beginStored(event('pointerdown',25,35),'stored');if(mode!=='click')v.window.emit(event('pointermove',35,45));if(mode==='cancel')v.cancel();if(mode==='lost')v.svg.emit(event('lostpointercapture',0,0));if(mode==='source')v.props.source='new';if(mode==='revision')v.props.revision++;if(mode==='lock')v.props.inputLocked=true;if(mode==='dispose')v.dispose();v.window.emit(event('pointerup',mode==='click'?25:35,mode==='click'?35:45));await tick();assert.equal(v.commands.length,0,mode);assert.equal(v.hasGesture(),false,mode);assert.equal(v.window.count(),0,mode);}
});
test('controlled pre-exit flush saves existing dirty input while inputLocked rejects fresh gestures, and waits real native receipt',async()=>{
const f=setup(),wait=deferred();f.setEdit(properties.propertyDraft(draw,5,'text',false));f.props.inputLocked=true;f.props.onCommand=c=>{f.commands.push(c);return wait.promise;};f.beginStored(event('pointerdown',10,10),'stored');assert.equal(f.hasGesture(),false);
f.cancelUserEdit();assert.equal(f.edit().drawing.text,'draft');assert.ok(properties.drawingDrafts.get(f.props.port.draftKey()));
let finished=false;const work=f.flush(()=>true).then(()=>finished=true);await tick();assert.equal(f.pending(),true);assert.equal(finished,false);assert.equal(f.commands.length,1);wait.resolve();await work;assert.equal(finished,true);assert.equal(properties.drawingDrafts.get(f.props.port.draftKey()),undefined);
});
test('publish-before-receipt does not clear draft; failed save retains exact old CAS and newer drafts cannot be deleted by late success',async()=>{
const f=setup(),wait=deferred(),draft=properties.propertyDraft(draw,5,'text',false);f.setEdit(draft);f.props.onCommand=()=>wait.promise;const saving=f.saveText();await tick();f.props.revision=6;assert.equal(properties.drawingDrafts.get(f.props.port.draftKey()),draft);
const newer={...draft,drawing:{...draw,text:'newer'}};properties.drawingDrafts.set(f.props.port.draftKey(),newer);wait.resolve();await saving;assert.equal(properties.drawingDrafts.get(f.props.port.draftKey()),newer);properties.drawingDrafts.delete(f.props.port.draftKey());
const failed=setup();failed.setEdit(draft);failed.props.onCommand=async()=>{throw Error('CAS failed');};assert.equal(await failed.saveText(),false);assert.equal(failed.edit().expectedRevision,5);assert.equal(failed.edit().drawing.text,'draft');assert.equal(properties.drawingDrafts.get(failed.props.port.draftKey()).error,'保存失败');failed.dispose();assert.equal(properties.drawingDrafts.get(failed.props.port.draftKey()).drawing.text,'draft');properties.drawingDrafts.delete(failed.props.port.draftKey());
});
test('video Done retains annotations and closes; screenshot Done still exports before close',async()=>{
const video=setup();await video.done();assert.deepEqual(video.out,['close']);const image=setup();image.props.retainOnDone=false;await image.done();assert.deepEqual(image.out,['export','close']);
});
test('selected getter completion cannot open content for a successor selection/source or discard an existing draft',async()=>{
const f=setup(),wait=deferred();f.props.port.ensureEditable=()=>wait.promise;const pending=f.ensureSelection('stored');assert.equal(f.reading(),true);f.selected('other');wait.resolve(draw);assert.equal(await pending,undefined);assert.equal(f.reading(),false);assert.equal(f.edit(),undefined);
});
test('actual shared double-click opens uncached native text after deferred exact-ref read, without authoring or a cached drawing',async()=>{
const f=setup(),wait=deferred(),literal={...draw,id:'stored',text:' 旧\t<&>\n正文 '};let reads=0;
f.props.port.stored=()=>[{id:'stored',kind:'text',bounds:{x:5,y:6,width:24,height:26}}];f.props.port.ensureEditable=id=>{assert.equal(id,'stored');reads++;return wait.promise;};
const group={getAttribute:key=>key==='data-drawing-id'?'stored':null},hit={closest:selector=>selector==='[data-drawing-id]'?group:null};f.svg.contains=node=>node===hit||node===group;f.svg.getBoundingClientRect=()=>({left:10,top:20,right:210,bottom:70,width:200,height:50});
const previousDocument=globalThis.document;globalThis.document={elementsFromPoint:()=>[hit,f.svg]};
try{f.doubleClick(event('dblclick',10,10));assert.equal(reads,1);assert.equal(f.reading(),true);assert.equal(f.edit(),undefined);assert.equal(f.commands.length,0);wait.resolve(literal);await tick();assert.equal(f.edit().drawing.text,literal.text);assert.equal(f.edit().expectedRevision,5);assert.equal(f.edit().base.text,literal.text);assert.equal(f.commands.length,0);}finally{globalThis.document=previousDocument;f.dispose();properties.drawingDrafts.delete(f.props.port.draftKey());}
});
test('cold text double-click retains selection/source/disposal fences and reports failed native reads without opening or writing',async()=>{
for(const mode of ['selection','source','dispose','locked','failure']){
const f=setup(),wait=deferred();f.props.port.stored=()=>[{id:'stored',kind:'text',bounds:{x:5,y:6,width:24,height:26}}];f.props.port.ensureEditable=()=>wait.promise;
const group={getAttribute:()=> 'stored'},hit={closest:selector=>selector==='[data-drawing-id]'?group:null};f.svg.contains=node=>node===hit||node===group;f.svg.getBoundingClientRect=()=>({left:10,top:20,right:210,bottom:70,width:200,height:50});const previousDocument=globalThis.document;globalThis.document={elementsFromPoint:()=>[hit,f.svg]};
try{f.doubleClick(event('dblclick',10,10));assert.equal(f.reading(),true);if(mode==='selection')f.selected('successor');if(mode==='source')f.props.port.draftKey=()=>JSON.stringify(['scene','videoDrawing','successor']);if(mode==='dispose')f.dispose();if(mode==='locked')f.props.inputLocked=true;if(mode==='failure')wait.reject(Error('native exact ref rejected'));else wait.resolve({...draw,id:'stored'});await tick();assert.equal(f.edit(),undefined,mode);assert.equal(f.commands.length,0,mode);if(mode==='failure')assert.deepEqual(f.errors,['native exact ref rejected']);}finally{globalThis.document=previousDocument;f.dispose();properties.drawingDrafts.delete(f.props.port.draftKey());}
}
});
