using mewu_ai_Assistant.AI;
using mewu_ai_Assistant.Models;
using mewu_ai_Assistant.Services;
using System.Text.Json;
using Xunit;
namespace MewuAI.Tests;
public sealed class ServicesTests
{
    [Fact] public void CredentialService_RoundTripsWithCurrentUserDpapi(){var root=TestDirectory();try{var service=new CredentialService(root);service.Save("credential","secret-value");Assert.Equal("secret-value",service.Read("credential"));service.Delete("credential");Assert.Null(service.Read("credential"));}finally{Directory.Delete(root,true);}}
    [Fact] public void CredentialService_RejectsPathTraversalIdentifiers(){var root=TestDirectory();try{var service=new CredentialService(root);Assert.Throws<ArgumentException>(()=>service.Save("..\\outside","secret"));Assert.False(File.Exists(Path.Combine(Directory.GetParent(root)!.FullName,"outside.bin")));}finally{Directory.Delete(root,true);}}
    [Fact] public void SettingsService_RoundTripsProvidersAndEnums(){var root=TestDirectory();try{var path=Path.Combine(root,"settings.json");var settings=new AppSettings{CaptureDelaySeconds=5,IncludeCaptureCursor=true,VoiceLanguage="zh-CN",CaptureHotkey=new(){Key=System.Windows.Input.Key.Z,Modifiers=System.Windows.Input.ModifierKeys.Control|System.Windows.Input.ModifierKeys.Alt},Providers=[new(){Name="私有模型",Type="OpenAICompatible",BaseUrl="https://example.invalid/v1",Model="model-a",CustomHeaders=new(){{"X-Tenant","demo"}}}]};settings.DefaultProviderId=settings.Providers[0].Id;var service=new SettingsService(path);service.Save(settings);var loaded=service.Load();Assert.Equal(5,loaded.CaptureDelaySeconds);Assert.Equal(System.Windows.Input.Key.Z,loaded.CaptureHotkey.Key);Assert.Equal("model-a",loaded.Providers.Single().Model);Assert.Equal("demo",loaded.Providers.Single().CustomHeaders["X-Tenant"]);using var document=JsonDocument.Parse(File.ReadAllText(path));Assert.False(document.RootElement.ToString().Contains("secret",StringComparison.OrdinalIgnoreCase));}finally{Directory.Delete(root,true);}}
    [Fact] public void SettingsService_NormalizesUnsafeNumericValues(){var root=TestDirectory();try{var path=Path.Combine(root,"settings.json");File.WriteAllText(path,"{\"RecordingFps\":999,\"RecordingQuality\":-1,\"GifFps\":0,\"TempCleanupDays\":999,\"OverlayOpacity\":9}");var loaded=new SettingsService(path).Load();Assert.Equal(60,loaded.RecordingFps);Assert.Equal(20,loaded.RecordingQuality);Assert.Equal(1,loaded.GifFps);Assert.Equal(30,loaded.TempCleanupDays);Assert.Equal(.75,loaded.OverlayOpacity);}finally{Directory.Delete(root,true);}}
    [Fact] public void TempFileService_CleansOnlyExpiredEntries(){var root=TestDirectory();try{var service=new TempFileService(root);var old=Path.Combine(root,"old.tmp");var fresh=Path.Combine(root,"fresh.tmp");File.WriteAllText(old,"old");File.WriteAllText(fresh,"fresh");File.SetLastWriteTimeUtc(old,DateTime.UtcNow-TimeSpan.FromDays(5));service.Cleanup(TimeSpan.FromDays(3));Assert.False(File.Exists(old));Assert.True(File.Exists(fresh));}finally{Directory.Delete(root,true);}}
    [Fact] public void PrivacyLogger_RedactsAuthorizationAndApiKeys(){var root=TestDirectory();try{new PrivacyLogger(root).Error("AI",new InvalidOperationException("Authorization: Bearer token-123 api_key=secret-456"));var text=File.ReadAllText(Directory.GetFiles(root,"*.log").Single());Assert.DoesNotContain("token-123",text);Assert.DoesNotContain("secret-456",text);Assert.Contains("[REDACTED]",text);}finally{Directory.Delete(root,true);}}
    [Fact] public void MiniMaxM3Provider_EnablesNativeImageAndVideoUnderstanding(){var provider=new MiniMaxProvider(new AiProviderSettings{Type="MiniMax",BaseUrl="https://api.minimax.io/v1",Model="MiniMax-M3"},"unused");Assert.True(provider.Capabilities.SupportsImage);Assert.True(provider.Capabilities.SupportsVideo);Assert.Contains("image/png",provider.Capabilities.AcceptedMimeTypes);Assert.Contains("video/mp4",provider.Capabilities.AcceptedMimeTypes);Assert.Equal(50L*1024*1024,provider.Capabilities.MaxAttachmentSize);}
    [Fact] public void OlderMiniMaxModel_DoesNotClaimM3MultimodalProtocol(){var provider=new MiniMaxProvider(new AiProviderSettings{Type="MiniMax",BaseUrl="https://api.minimax.io/v1",Model="MiniMax-M2.7"},"unused");Assert.False(provider.Capabilities.SupportsImage);Assert.False(provider.Capabilities.SupportsVideo);}
    [Fact] public void OpenAiProvider_DeclaresSupportedImageMimeTypes(){var provider=new OpenAiCompatibleProvider(new AiProviderSettings(),"unused");Assert.Contains("image/png",provider.Capabilities.AcceptedMimeTypes);Assert.False(provider.Capabilities.SupportsVideo);}
    [Fact] public async Task GenericOpenAiProvider_RejectsVideoBeforeNetwork(){var provider=new OpenAiCompatibleProvider(new AiProviderSettings(),"unused");await Assert.ThrowsAsync<NotSupportedException>(()=>provider.SendAsync(new AiRequest{Attachments=[new(AiAttachmentType.Video,"video/mp4",[1,2,3])]},TestContext.Current.CancellationToken));}
    [Fact] public async Task OpenAiProvider_RejectsUnsupportedMimeBeforeNetwork(){var provider=new OpenAiCompatibleProvider(new AiProviderSettings(),"unused");await Assert.ThrowsAsync<NotSupportedException>(()=>provider.SendAsync(new AiRequest{Attachments=[new(AiAttachmentType.Image,"image/bmp",[1,2,3])]},TestContext.Current.CancellationToken));}
    private static string TestDirectory(){var path=Path.Combine(Path.GetTempPath(),"MewuAI.Tests",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(path);return path;}
}
