using mewu_ai_Assistant.AI;
using mewu_ai_Assistant.Models;
using mewu_ai_Assistant.Services;
using System.Text.Json;
using Xunit;
namespace MewuAI.Tests;
public sealed class ServicesTests
{
    [Fact] public void CredentialService_RoundTripsWithCurrentUserDpapi(){var root=TestDirectory();try{var service=new CredentialService(root);service.Save("credential","secret-value");Assert.Equal("secret-value",service.Read("credential"));service.Delete("credential");Assert.Null(service.Read("credential"));}finally{Directory.Delete(root,true);}}
    [Fact] public void SettingsService_RoundTripsProvidersAndEnums(){var root=TestDirectory();try{var path=Path.Combine(root,"settings.json");var settings=new AppSettings{CaptureDelaySeconds=5,IncludeCaptureCursor=true,VoiceLanguage="zh-CN",CaptureHotkey=new(){Key=System.Windows.Input.Key.Z,Modifiers=System.Windows.Input.ModifierKeys.Control|System.Windows.Input.ModifierKeys.Alt},Providers=[new(){Name="私有模型",Type="OpenAICompatible",BaseUrl="https://example.invalid/v1",Model="model-a",CustomHeaders=new(){{"X-Tenant","demo"}}}]};settings.DefaultProviderId=settings.Providers[0].Id;var service=new SettingsService(path);service.Save(settings);var loaded=service.Load();Assert.Equal(5,loaded.CaptureDelaySeconds);Assert.Equal(System.Windows.Input.Key.Z,loaded.CaptureHotkey.Key);Assert.Equal("model-a",loaded.Providers.Single().Model);Assert.Equal("demo",loaded.Providers.Single().CustomHeaders["X-Tenant"]);using var document=JsonDocument.Parse(File.ReadAllText(path));Assert.False(document.RootElement.ToString().Contains("secret",StringComparison.OrdinalIgnoreCase));}finally{Directory.Delete(root,true);}}
    [Fact] public void TempFileService_CleansOnlyExpiredEntries(){var root=TestDirectory();try{var service=new TempFileService(root);var old=Path.Combine(root,"old.tmp");var fresh=Path.Combine(root,"fresh.tmp");File.WriteAllText(old,"old");File.WriteAllText(fresh,"fresh");File.SetLastWriteTimeUtc(old,DateTime.UtcNow-TimeSpan.FromDays(5));service.Cleanup(TimeSpan.FromDays(3));Assert.False(File.Exists(old));Assert.True(File.Exists(fresh));}finally{Directory.Delete(root,true);}}
    [Fact] public void PrivacyLogger_RedactsAuthorizationAndApiKeys(){var root=TestDirectory();try{new PrivacyLogger(root).Error("AI",new InvalidOperationException("Authorization: Bearer token-123 api_key=secret-456"));var text=File.ReadAllText(Directory.GetFiles(root,"*.log").Single());Assert.DoesNotContain("token-123",text);Assert.DoesNotContain("secret-456",text);Assert.Contains("[REDACTED]",text);}finally{Directory.Delete(root,true);}}
    [Fact] public void MiniMaxProvider_RejectsImageBeforeNetwork(){var provider=new MiniMaxProvider(new AiProviderSettings{Type="MiniMax",BaseUrl="https://api.minimax.io/v1",Model="MiniMax-M2.7"},"unused");Assert.False(provider.Capabilities.SupportsImage);}
    [Fact] public void OpenAiProvider_DeclaresSupportedImageMimeTypes(){var provider=new OpenAiCompatibleProvider(new AiProviderSettings(),"unused");Assert.Contains("image/png",provider.Capabilities.AcceptedMimeTypes);Assert.False(provider.Capabilities.SupportsVideo);}
    private static string TestDirectory(){var path=Path.Combine(Path.GetTempPath(),"MewuAI.Tests",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(path);return path;}
}
